name: CI/CD

on: [push]

jobs:
  build_and_test:
    name: Runs build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #dotnet-version: #['3.0', '3.1.x', '5.0.x' ]
        dotnet-version: ['3.1.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        #run: dotnet test --no-build --no-restore --verbosity normal tests/curso.api.tests/curso.api.tests.csproj
        # run: dotnet test --collect:"XPlat Code Coverage"
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
      # - name: Upload TestResults XML
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: TestResults
      #     path: /home/runner/work/course/course/tests/curso.api.tests/TestResults/

  publish:
    name: Publish apps
    needs: [build_and_test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #dotnet-version: #['3.0', '3.1.x', '5.0.x' ]
        dotnet-version: ['3.1.x']

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: publish
      run:  dotnet publish
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApi
        path: /home/runner/work/course/course/course.api/bin/Debug/netcoreapp3.1/publish/
        
    - name: Upload WebApp2 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Front
        path: /home/runner/work/course/course/curso.mvc.web/bin/Debug/netcoreapp3.1/publish/